### ISSUE TITLE
apt repo is not served any more

### ISSUE THREAD

**Issue by vzts** [mayfieldrobotics/ros-webrtc#100]
https://github.com/MayfieldRoboticsPublic/ros-webrtc/commit/b1684d312d63bc9a4bceb8d9498c7f25c90f0d24#diff-acd8ef24d2ddda52a7fed977bd557bddR2

`jingle_apt_repo: "http://apt-tm8ji0.c2x.io"` doesn't seem to be served any more.

**Comment by vzts** [comment]
Just asking, is this repo still maintained at all? It's heart breaking that Mayfield Robotics has been shut down... I'm curious if any one is maintaining this repo. trying to make a maintained fork if not.

**Comment by vzts** [comment]
@spmaniato @hopewm @cjwilliams @po1 sorry if I bothered you, I wasn't sure who's on the mailing list for the issues

**Comment by po1** [comment]
Hi @vzts, sorry about the lag. Unfortunately, it seems that the repo was shutdown along with all mayfield resources. Former mayfielders have no more access to it than you do :/

Likely you will have to find and/or rebuild libjingle yourself and host an apt repo somewhere.

**Comment by vzts** [comment]
@po1 thank you for the reply!
