### ISSUE TITLE
verify installable into ros workspace

### ISSUE THREAD

**Issue by aisch** [mayfieldrobotics/ros-webrtc#2]
either via `rosinstall` or `*_depends`. has a bunch of system dependencies:
- libjingle
-  ...

so anticipate problems.

**Comment by boblee311** [comment]
This webpage [https://github.com/ixirobot/webrtc-build](https://github.com/ixirobot/webrtc-build) doesnt exist anymore. Could you provide more light on how to fix dependency issues, especially with the libjingle?

**Comment by mpena2099** [comment]
Same problem on install: 
-- Checking for module 'libjingle555cfe9'
--   No package 'libjingle555cfe9' found
